# GitLab CI snippet (merge blocker)
# Assumes your pipeline already runs a Sonar scan that generates report-task.txt.

sonar_quality_gate:
  image: python:3.11-slim
  stage: test
  variables:
    SONAR_TIMEOUT_SECONDS: "600"
    SONAR_POLL_SECONDS: "5"
  script:
    - python3 zeid_data_sonar_merge_blocker.py --json
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

# Required CI variables (set in GitLab UI as masked/protected):
#   SONAR_HOST_URL
#   SONAR_TOKEN
